version: '3'

services:
  openresty_proxy:
    hostname: openresty_proxy
    container_name: openresty_proxy
    ports:
      - 8080:80
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfiles/openresty/Dockerfile

